### PR TITLE
I made my homework, needs some work

### PR DESCRIPTION
**Pull request by Kani103**

### CODE REVIEW

**Comment by danlaudk** [comment]
overall, taking shape in right direction so that's good. should be fixed: should be foreign keys. insert :id shouldn't (won't) work with auto-increment. :id shouldn't be in all routes  (see my (dan) post in slack to #class ).

**Comment by danlaudk** [comment]
:id should not be in POST routes. GET requests are not supported. Otherwise design is good.  Please include two foreign keys. Please submit a working app *and a database dump* file (eg dump.sql) that is created AFTER you have made successful Post request (and i will run a GET against it to test)

**Comment by wouterkleijn** [comment]
Thanks for reviewing @danlaudk Please have a look @Kani103

**Comment by wouterkleijn** [comment]
Thanks @Kani103 , what about the changes @danlaudk - any further feedback?

**Pull request closed without merging**
