### PR TITLE
week3

### PR DESCRIPTION
**Pull request by sigma21**
Hello @wouterkleijn!
I forgot my laptop charger somewhere and finally got it yesterday so I just started doing the homework but I'm not done yet. I'll need a couple more days until it is fully finished. Sorry for the delay.

### CODE REVIEW

**Comment by wouterkleijn** [comment]
@sigma21 Thank you for your communication upfront and submitting something anyway. No problem

**Comment by danlaudk** [comment]
@sigma21 please submit ur db schema as soon as u have code that makes one sucessful database request thru the api

**Comment by sigma21** [comment]
Hey @danlaudk I've updated the code. Check it out please.

**Comment by danlaudk** [comment]
createConnection needs to specify the database name, and also your dump file should indicate the name of the database (eg by creating it)

**Pull request closed without merging**
