### PR TITLE
Week3 mongo js

### PR DESCRIPTION
**Pull request by danlaudk**

### CODE REVIEW

**Comment by danlaudk** [comment]
What if each pair looks only at one file? Then come back to discuss

Op ma 23 mrt. 2020 15:58 schreef Noer <notifications@github.com>:

**Comment by danlaudk** [comment]
awaiting Noer's assessment of whether to switch over to a schema-focused rather than syntax-focused mongo lesson. Slack conversation

**Comment by danlaunl** [comment]
superceded by Mongo weeks 3,4 in May 2022. can probably be closed/deleted (i think i dont have permissions)

**Comment by robvk** [comment]
You are right, thanks for the effort @danlaunl !

**Pull request closed without merging**
