### PR TITLE
dbWeek3 not finished missing dumb file and many errors

### PR DESCRIPTION
**Pull request by saidcetinkaya**

### CODE REVIEW

**Comment by danlaudk** [comment]
awaiting fix of errors. can't review db elements until dump file is provided

**Comment by saidcetinkaya** [comment]
still working on it 👍

**Comment by wouterkleijn** [comment]
Dear @saidcetinkaya Can you make the necessary changes?

**Comment by wouterkleijn** [comment]
Reminder!

**Pull request closed without merging**
